#adapted from example in docker documentation
version: '3'

services:
  redis:
    container_name: redis
    image: redis
    ports:
      - "6379:6379"
    volumes:
      - ../data/redis:/data
    entrypoint: redis-server --appendonly yes
    restart: always

  web:
    build: .
    volumes:
      - .:/code
    expose:
      - 8000
    command: python /code/helloWorld/manage.py runserver 0.0.0.0:8000

  nginx:
    restart: always
    build: ./nginx/
    depends_on:
      - web
    ports:
      - "80:80"
    links:
      - web:web